version: 2.1

executors:
  docker-circleci:
    working_directory: "~/repo"
    docker:
      - image: "circleci/node:10.12-stretch-browsers"

jobs:
  test:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: ./node_modules/.bin/jspm install
      - run: ./node_modules/.bin/karma start --single-run
  build:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: ./node_modules/.bin/jspm install
      - run: ./node_modules/.bin/gulp build
      
workflows:
  build_test:
    jobs:
      - test
      - build
