version: 2.1

executors:
  docker-circleci:
    working_directory: "~/repo"
    docker:
      - image: "circleci/node:10.12-stretch-browsers"

jobs:
  build_test:
    executor: docker-circleci
    steps:
      - run: npm i -g jspm
      - checkout
      - run: npm ci
      - run: jspm install
      - run: npm run test
      
workflows:
  build_test:
    jobs:
      - build_test
